language: cpp

compiler:
  - gcc

install:
  - sudo apt-get install cmake valgrind

before_script:
  - mkdir build
  - cd build
  - cmake -DLIBJ_USE_THREAD=ON -DLIBJ_USE_XML=ON -DLIBJ_BUILD_TEST=ON ..

script:
  - make

after_script:
  - gtest/libj-test
  - valgrind --leak-check=full gtest/libj-test
